<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
    <AssemblyName>PixelRecolor</AssemblyName>
    <RootNamespace>PixelRecolor</RootNamespace>
    <Product>PixelRecolor</Product>
    <Title>PixelRecolor</Title>
  </PropertyGroup>

</Project>
